# Generated by Django 5.2.6 on 2025-09-07 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredienttype',
            name='category',
            field=models.CharField(choices=[('vegetal', 'Vegetal'), ('animal', 'Animal'), ('mineral', 'Mineral'), ('procesado', 'Procesado'), ('ultraprocesado', 'Ultraprocesado')], max_length=20),
        ),
    ]
