# Generated by Django 5.2.6 on 2025-09-08 02:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_ingredienttype_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredienttype',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_types', to=settings.AUTH_USER_MODEL),
        ),
    ]
