# Generated by Django 5.2.6 on 2025-09-08 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_ingredienttype_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.CharField(choices=[('plato fuerte', 'Plato fuerte'), ('entrada', 'Entrada'), ('pasabocas', 'Pasabocas'), ('postre', 'Postre'), ('acompañamiento', 'Acompañamiento'), ('ensalada', 'Ensalada'), ('bebida', 'Bebida')], default='plato fuerte', max_length=20),
        ),
    ]
