# Generated by Django 5.2.6 on 2025-09-09 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_recipe_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multimedia',
            name='file',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
