# Generated by Django 5.2.6 on 2025-09-09 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_multimedia_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multimedia',
            name='file',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
