# Generated by Django 5.2.6 on 2025-11-04 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_multimedia_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='recipes/'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
