# Generated by Django 5.2.6 on 2025-11-04 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_recipe_image_file_recipe_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='image_file',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='image_url',
        ),
    ]
